# Generated by Django 4.2.4 on 2023-12-05 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0003_userprofile_professor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="name",
        ),
        migrations.AddField(
            model_name="exam",
            name="descripcion",
            field=models.TextField(default="Descripción predeterminada"),
        ),
        migrations.AddField(
            model_name="exam",
            name="duracion",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exam",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="subject",
            name="nombre",
            field=models.CharField(default="Nombre predeterminado", max_length=255),
        ),
        migrations.AlterField(
            model_name="exam",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
