# Generated by Django 4.2.4 on 2023-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_exam_subject_remove_subject_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaDesarrollo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PreguntaSeleccionMultiple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("opciones", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="PreguntaVerdaderoFalso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("respuesta_correcta", models.BooleanField()),
            ],
        ),
    ]
