# Generated by Django 4.2.4 on 2023-12-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_preguntadesarrollo_preguntaseleccionmultiple_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preguntadesarrollo",
            name="examen",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.exam",
            ),
        ),
        migrations.AddField(
            model_name="preguntaseleccionmultiple",
            name="examen",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.exam",
            ),
        ),
        migrations.AddField(
            model_name="preguntaverdaderofalso",
            name="examen",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.exam",
            ),
        ),
    ]
