# Generated by Django 4.2.4 on 2023-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_preguntadesarrollo_examen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VF", "Verdadero/Falso"),
                            ("SM", "Selección Múltiple"),
                            ("DEV", "Desarrollo"),
                        ],
                        max_length=3,
                    ),
                ),
                ("enunciado", models.TextField()),
                ("es_verdadero", models.BooleanField(blank=True, null=True)),
                ("opciones", models.JSONField(blank=True, null=True)),
                ("opcion_correcta", models.IntegerField(blank=True, null=True)),
                ("respuesta_desarrollo", models.TextField(blank=True, null=True)),
                ("puntaje", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="preguntaseleccionmultiple",
            name="examen",
        ),
        migrations.RemoveField(
            model_name="preguntaverdaderofalso",
            name="examen",
        ),
        migrations.DeleteModel(
            name="PreguntaDesarrollo",
        ),
        migrations.DeleteModel(
            name="PreguntaSeleccionMultiple",
        ),
        migrations.DeleteModel(
            name="PreguntaVerdaderoFalso",
        ),
    ]
