# Generated by Django 4.2.4 on 2023-12-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_pregunta_examen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pregunta",
            name="opciones",
        ),
        migrations.AddField(
            model_name="opcion",
            name="pregunta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.pregunta",
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="examen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.exam"
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="opcion_correcta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="respuesta_correcta",
                to="account.opcion",
            ),
        ),
        migrations.AlterModelTable(
            name="pregunta",
            table="account_pregunta",
        ),
    ]
