# Generated by Django 4.2.4 on 2023-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_remove_pregunta_opciones_opcion_pregunta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="dificultad",
            field=models.CharField(default="Dificultad predeterminada", max_length=255),
        ),
        migrations.AddField(
            model_name="exam",
            name="materia",
            field=models.CharField(default="Materia predeterminada", max_length=255),
        ),
        migrations.AddField(
            model_name="exam",
            name="num_questions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exam",
            name="quiz_type",
            field=models.CharField(default="Quiz predeterminado", max_length=255),
        ),
    ]
