# Generated by Django 4.2.4 on 2023-12-09 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_exam_dificultad_exam_materia_exam_num_questions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opcion",
            name="pregunta",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="examen",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="opcion_correcta",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="subjects_taught",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="professor",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.DeleteModel(
            name="Opcion",
        ),
        migrations.DeleteModel(
            name="Pregunta",
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
