# Generated by Django 4.2.4 on 2023-12-09 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Archivo",
        ),
    ]
