# Generated by Django 4.1.4 on 2024-01-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cubaapp", "0004_rename_user_message_sender_chat_message_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="cubaapp.chat",
            ),
        ),
    ]
