# Generated by Django 4.1.4 on 2024-01-09 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cubaapp", "0006_alter_message_chat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="sender",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
    ]
