# Generated by Django 4.1.4 on 2024-01-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cubaapp", "0008_message_chat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.AddField(
            model_name="chat",
            name="ai_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_ai_message",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cubaapp.chat"
            ),
        ),
    ]
