# Generated by Django 4.1.4 on 2024-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cubaapp", "0010_remove_chat_ai_enabled_remove_chat_participants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
